version: '3'

services:
  web:
    image: httpd
    container_name: gf-web
    networks:
      - net
    ports:
      - 80:80
      - 443:80
    volumes:
      - gf-vol:/usr/local/apache2/htdocs
    restart: always
    
volumes:
  gf-vol:
    name: gf-vol
    driver: local

networks:
  net:
    name: gf-net
    